# Generated by Django 2.2 on 2020-05-10 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggonderi',
            name='eposta',
            field=models.EmailField(default='yok@yok.com', max_length=254),
        ),
        migrations.AddField(
            model_name='bloggonderi',
            name='yazar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
